# Generated by Django 4.2.6 on 2023-10-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='projects.project'),
        ),
    ]
