# Generated by Django 4.2.6 on 2023-10-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_commentreport_project_commentreport_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
