# Generated by Django 4.2.6 on 2023-10-21 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_by_project_current_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
