# Generated by Django 4.2.6 on 2023-10-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_commentreport_created_at'),
        ('projects', '0005_project_created_at_project_is_featured_and_more'),
    ]

    operations = [
    ]
