# Generated by Django 4.2.6 on 2023-10-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_merge_20231026_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreport',
            name='created_at',
        ),
    ]
