# Generated by Django 3.2.22 on 2023-10-19 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountregisteration',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/accounts/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountregisteration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
