# Generated by Django 3.2.22 on 2023-10-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231019_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountRegisteration',
        ),
    ]
