# Generated by Django 3.2.12 on 2023-10-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
    ]
